#!/bin/sh
###############################################################################
#  Copyright (C) 2008, 2011 SES ENGINEERING, Luxembourg S.A.R.L.
#
# This file is part of SPELL.
#
# SPELL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SPELL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SPELL. If not, see <http://www.gnu.org/licenses/>.
#
# FILE: Cleanup script for SPELL servers
#
# DATE: 24/11/2008
#
###############################################################################


#===============================================================================
# Setup main environment variables
#===============================================================================
# SPELL home
if [[ -z "$SPELL_HOME" ]]
then
    echo "ERROR: SPELL_HOME environment variable is not defined"
    exit 1
else
    [[ ! -d $SPELL_HOME ]] && echo "ERROR: cannot find SPELL home directory: $SPELL_HOME" && exit 1
fi
echo "SPELL home: $SPELL_HOME"

CONFIG=$1

if [[ -z "$1" ]]
then
	echo "Must provide the configuration file name, eg: $0 simtec3_7"
	exit 1
fi

PIDS=`ps aux | grep $SPELL_HOME | grep $CONFIG | awk '{print $2}'`

for PID in $PIDS
do
	kill -9 $PID
done

